### PR TITLE
Return BadRequest if the json is incorrect

### LINKED ISSUE #28: Return better error status code
We need to improve the status code returned by compendium. For example, if the json is [incorrect](https://github.com/higherkindness/compendium/blob/11d731e2ea10d8e800ff24d87a684c4bada0709c/src/main/scala/higherkindness/compendium/http/RootService.scala#L46) we should return a `Bad request` instead of `Internal server error`.

### PR DESCRIPTION
**Pull request by pirita**
Fixes #28

### CODE REVIEW

File: modules/server/src/test/scala/higherkindness/compendium/http/RootServiceSpec.scala [hunk 1]
```diff
@@ -93,6 +95,23 @@ object RootServiceSpec extends Specification with ScalaCheck {
         .map(_.value) === Some(s"/protocol/$id")
     }.setGen(Gen.alphaNumStr suchThat (!_.isEmpty))
 
+    "If json is invalid returns a 422 Unprocessable entity" >> prop { id: String =>
```
Comment (JesusMtnez) [inline modules/server/src/test/scala/higherkindness/compendium/http/RootServiceSpec.scala]: Test description is wrong
```suggestion
    "If json is invalid returns a 400 Bad Request" >> prop { id: String =>
```

File: modules/server/src/main/scala/higherkindness/compendium/http/RootService.scala [hunk 2]
```diff
@@ -46,7 +46,8 @@ object RootService {
           } yield resp.putHeaders(Location(req.uri.withPath(s"${req.uri.path}")))
         ) {
           case e: org.apache.avro.SchemaParseException => BadRequest(ErrorResponse(e.getMessage))
-          case _                                       => InternalServerError()
+          case e: org.http4s.InvalidMessageBodyFailure => BadRequest(ErrorResponse(e.getMessage))
+          case e => InternalServerError()
```
Comment (JesusMtnez) [inline modules/server/src/main/scala/higherkindness/compendium/http/RootService.scala]:
```suggestion
          case _ => InternalServerError()
```
